Cart/urls.py
from django.urls import path

from Cart.views import *
from Cart import views


urlpatterns = [
    path('cartview/', views.cart_details, name="cart_details"),
]

ecommerce/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url
# from store.views import shop_page, category_wise_product
from store.api import *


urlpatterns = [
    path('admin/', admin.site.urls),

    ## Path for Cart ##

    path('cart/', include('Cart.urls')),

    ## Path for Store App ##

    path('', include("store.urls")),


    ## Apis ##

    path('api/api_add_to_cart/', api_add_to_cart, name="api_add_to_cart"),
    path('api/api_remove_from_cart/', api_remove_from_cart, name="api_remove_from_cart"),
    path('api/api_checkout/', api_checkout, name="api_checkout"),


    url(r'^media/(?P<path>.*)$', serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from .views import (homeView, productDetailView, allBrandsView, userDashboardView,
                    manageProfileView, wishlistView, campaignView, flashSaleView,
                    shopwiseProductView, localShopView, searchView,
                    user_registration, user_login, logoutView,
                    categorywiseProductView, subcategorywiseProduct, brandwiseProductView, get_seller_registration)


app_name = "store"
urlpatterns = [
    path("", homeView, name="home"),
    path("product/<str:slug>/", productDetailView, name="product-detail"),
    path("brands/", allBrandsView, name="brands"),
    path("dashboard/", userDashboardView, name="dashboard"),
    path("profile/", manageProfileView, name="profile"),
    path("wishlist/", wishlistView, name="wishlist"),
    path("campaigns/", campaignView, name="campaigns"),
    path("flash-sale/", flashSaleView, name="flash-sale"),
    path("shops/<int:id>/<str:title>/", shopwiseProductView, name="shopwise-product"),
    path("categories/<int:id>/<str:title>/", categorywiseProductView, name="categorywise-product"),
    path("subcategories/<int:id>/<str:title>/", subcategorywiseProduct, name="subcategorywise-product"),
    path("brands/<int:id>/<str:title>/", brandwiseProductView, name="brandwise-product"),
    path("localshop/Mustaqeem-Localshop", localShopView, name="localshop"),
    path("search/", searchView, name="search"),

    ## Login Registration ##

    path("user_registration/", user_registration, name="user_registration"),
    path("user_login/", user_login, name="user_login"),
    path('logout/', logoutView, name='logout'),

    ## Seller Registration ##

    path('seller_registration/', get_seller_registration, name="get_seller_registration"),
]

store/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


from store.models import *


class UserRegistrationForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SellerRegistrationForm(ModelForm):
    class Meta:
        model = Seller
        fields = '__all__'

store/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import (Category, Banner, SubCategory, Product, Shop, Campaign, Offer, Brand,
                    WishList, )
# Pagination module
from django.core.paginator import Paginator
from .forms import UserRegistrationForm, SellerRegistrationForm
from django.contrib.auth import login, logout, authenticate

# Create your views here.


def homeView(request):
    campaigns, offers, shops = None, None, None
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    shop_obj = Shop.objects.all()
    campaign_obj = Campaign.objects.all()
    offer_obj = Offer.objects.all()
    brands = Brand.objects.all().order_by("-id")

    if len(shop_obj) > 0:
        shops = Shop.objects.all().order_by("-id")[:6]
    if len(campaign_obj) > 0:
        campaigns = Campaign.objects.all().order_by("-id")[0]
    if len(offer_obj) > 0:
        offers = Offer.objects.all().order_by("-id")[0]

    banners, local_grocery_images, products, show_categories = None, None, None, None
    subcategories = SubCategory.objects.all()
    product_obj = Product.objects.all()
    show_category_obj = Category.objects.all()
    all_products = Product.objects.all().order_by("-id")

    if len(Banner.objects.all()) > 0:
        banners = Banner.objects.all().order_by("-id")[:6]
    if len(product_obj) > 0:
        products = Product.objects.all().order_by("-id")[:8]
    if len(show_category_obj) > 0:
        show_categories = Category.objects.all()[:6]

    context = {
        "categories": categories,
        "main_navbarCat": main_navbarCat,
        "shops": shops,
        "banners": banners,
        "subcategories": subcategories,
        "products": products,
        "show_categories": show_categories,
        "campaigns": campaigns,
        "offers": offers,
        "all_products": all_products,
        "brands": brands
    }
    return render(request, 'store/home.html', context)

## Login Registration View

def user_registration(request):
    categories = Category.objects.all().order_by("-id")
    form = UserRegistrationForm()
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:user_login')
    context = {'form': form, "categories": categories}
    return render(request, 'store/registration.html', context)


def user_login(request):
    categories = Category.objects.all().order_by("-id")
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)

            return redirect("store:home")

    context = {"categories": categories}
    return render(request, 'store/login.html', context)


def logoutView(request):
    logout(request)
    return redirect('store:home')


def productDetailView(request, slug):
    categories = Category.objects.all().order_by("-id")
    try:
        product = Product.objects.get(slug=slug)
    except Product.DoesNotExist:
        return HttpResponse("Product Not Found!")

    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()

    context = {
        "product": product,
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories
    }
    return render(request, "store/product_details.html", context)


def allBrandsView(request):
    categories = Category.objects.all().order_by("-id")
    brands = Brand.objects.all()
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()

    context = {
        "brands": brands,
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories
    }
    return render(request, "store/all_brands.html", context)


def userDashboardView(request):
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()

    context = {
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
        # "order_items": order_items
    }
    return render(request, "store/user_dashboard.html", context)


def manageProfileView(request):
    categories = Category.objects.all().order_by("-id")
    if request.user.is_authenticated:
        main_navbarCat = Category.objects.all().order_by("-id")[:6]
        subcategories = SubCategory.objects.all()

        context = {
            "main_navbarCat": main_navbarCat,
            "categories": categories,
            "subcategories": subcategories,
        }
        return render(request, "store/manage_profile.html", context)
    else:
        return redirect("store:home")


def wishlistView(request):
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()
    if request.user.is_authenticated:
        all_products = WishList.objects.filter(user=request.user, isFavorite=True)
    else:
        return redirect("store:home")

    context = {
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
        "all_products": all_products
    }
    return render(request, "store/wishlist.html", context)



def campaignView(request):
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()
    campaigns = Campaign.objects.all()
    products = Product.objects.all().order_by("-id")

    context = {
        "campaigns": campaigns,
        "products": products,
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
    }
    return render(request, "store/campaigns.html", context)


def flashSaleView(request):
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()
    offers = Offer.objects.all()
    products = Product.objects.all().order_by("-id")

    context = {
        "offers": offers,
        "products": products,
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
    }
    return render(request, "store/flash_sale.html", context)


def shopwiseProductView(request, id, title):
    products = []
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()

    try:
        shop = Shop.objects.get(id=id, title=title)
    except Shop.DoesNotExist:
        return HttpResponse("Shop not found!")
    else:
        products_obj = Product.objects.all().order_by("-id")
        # Appending all the products of the shop
        for item in products_obj:
            if str(item.shop) == shop.title:
                products.append(item)

        # Pagination
        paginator = Paginator(products, 20)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


    context = {
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
        "shop": shop,
        "products": products,
        "page_obj": page_obj
    }
    return render(request, "store/shopwise_product.html", context)


def localShopView(request):
    products = []
    categories = Category.objects.all().order_by("-id")
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()

    try:
        shop = Shop.objects.get(title="Mustaqeem Localshop")
    except Shop.DoesNotExist:
        return HttpResponse("Shop not found!")
    else:
        products_obj = Product.objects.all().order_by("-id")
        # Appending all the products of the shop
        for item in products_obj:
            if str(item.shop) == shop.title:
                products.append(item)

        # Pagination
        paginator = Paginator(products, 20)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)


    context = {
        "main_navbarCat": main_navbarCat,
        "categories": categories,
        "subcategories": subcategories,
        "shop": shop,
        "products": products,
        "page_obj": page_obj
    }
    return render(request, "store/shopwise_product.html", context)


def searchView(request):
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    categories = Category.objects.all().order_by("-id")
    subcategories = SubCategory.objects.all()

    if  request.method == "GET":
        query = request.GET.get("query")

        if query is None:
            return redirect("store:home")

        products = Product.objects.filter(title__icontains=query).order_by("-id")

        # Pagination
        paginator = Paginator(products, 20)

        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'products': products,
            "page_obj": page_obj,
            "main_navbarCat": main_navbarCat,
            "categories": categories,
            "subcategories": subcategories,
        }
        return render(request, 'store/search.html', context)


def categorywiseProductView(request, id, title):
    products = []
    main_navbarCat = Category.objects.all().order_by("-id")[:6]
    subcategories = SubCategory.objects.all()
    categories = Category.objects.all().order_by("-id")

    try:

store/templates/store/brandwise_product.html
{% extends "store/base.html" %}

{% load mathfilters %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/categorywise_product.css' %}">

<div class="container mt-5">
    <!-- Shop header starts -->
    <div class="shop__info">
        <div class="shop__title">
            <h5 class="fw-bold">{{ brand.title }} <span class="iconify" data-icon="teenyicons:tick-outline" data-inline="false"></span></h5>
        </div>
    </div>
    <!-- Shop header ends -->
</div>
<hr/>
<div class="container my-5">
    <div class="shop__container">
        <!-- Shop sidebar starts -->
        <div class="shop__sidebar">
            <div class="card shop__card p-3">
                <h5 class="text-center">Categories</h5>
                <hr />
                {% if categories %}
                    <!-- Category list starts -->
                    {% for category in categories %}
                        <div class="category__list">
                            <a href="{% url 'store:categorywise-product' category.id category.title %}">
                                <h6 class="fw-bold cat__title text-dark">{{ category.title }}</h6>
                            </a>
                            <!-- Subcategory list starts -->
                            {% for subcategory in subcategories %}
                                {% if subcategory.parent_category.title == category.title %}
                                    <a href="{% url 'store:subcategorywise-product' subcategory.id subcategory.title %}" class="subcategory__list">
                                        <div>
                                            <small class="text-muted ps-3">{{ subcategory.title }}</small>
                                        </div>
                                    </a>
                                {% endif %}
                            {% endfor %}
                            <!-- Subcategory list ends -->
                        </div>
                    {% endfor %}
                    <!-- Category list ends -->
                {% endif %}
            </div>

            <!-- Price filter starts -->
            <div class="card p-3 mt-3 mb-5">
                <label for="price__filter" class="form-label">Price Range</label>
                <input type="range" min="0" max="100" value="0" class="form-range slider" id="price__filter">
                <p>Value: <span id="demo"></span></p>

                <script>
                    var slider = document.getElementById("price__filter");
                    var output = document.getElementById("demo");
                    output.innerHTML = slider.value;

                    slider.oninput = function() {
                      output.innerHTML = this.value;
                    }
                </script>
            </div>
            <!-- Price filter ends -->
        </div>
        <!-- Shop sidebar ends -->

        <!-- Products related to shop starts -->
        {% if products %}
        <div class="shop__content">
            <div class="shop__contentHeader mb-3">
                <h5 class="text-center">{{ brand.title }}</h5>
                <hr class="mb-4" />
            </div>
            <div class="shop__productContainer">
                {% for product in page_obj %}
                <div class="card product__card">
                    <div class="product__img">
                        <a href="{% url 'store:product-detail' product.slug %}">
                            <img src="{{ product.img.url }}" alt="">
                        </a>
                    </div>

                    <div class="product__info card-body mb-2">
                        <!-- Product description starts -->
                        {% if product.description %}
                            <a class="text-dark" href="{% url 'store:product-detail' product.slug %}">
                                <p class="product__description text-muted">{{ product.description }}</p>
                            </a>
                        {% endif %}
                        <!-- Product description ends -->

                        <!-- Product title starts -->
                        <a class="text-dark" href="{% url 'store:product-detail' product.slug %}">
                            <h5 class="product__title">{{ product.title }}</h5>
                        </a>
                        <!-- Product title ends -->

                        <!-- Product discount badge starts -->
                        {% if product.sale_price %}
                            <h5><span class="badge bg-danger discount__badge">{{ product.sale_price|div:product.market_price|mul:100|sub:100|abs|slugify|slice:":2" }}% OFF</span></h5>
                        {% endif %}
                        <!-- Product discount badge ends -->
                    </div>
                    <div class="product__bottom card-footer">
                        {% if product.sale_price %}
                            <p><span class="cross__price">{{ product.market_price }}৳</span> <span>{{ product.sale_price }}৳</span></p>
                        {% else %}
                            <p>{{ product.market_price }}৳</p>
                        {% endif %}
                            <a href="{% url 'store:product-detail' product.slug %}">
                                <button class="btn__styled">View Details</button>
                            </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- Products related to shop ends -->
        {% else %}
        <!-- No product found starts -->
        <div class="text-center">
            <h5 class="fw-bold">No product to show!</h5>
        </div>
        <!-- No product found ends -->
        {% endif %}
    </div>
</div>

<!-- Pagination starts -->
{% if products %}
<div class="container my-5">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <a class="btn btn-outline-success" href="?page=1">&laquo; First</a>
            {% endif %}

            <span class="mx-2 align-top">
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-success mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3"  %}
                        <a class="btn btn-outline-success mb-4" href="?page={{ num }}">{{ num }}</a>
                    {% endif %}
                {% endfor %}
            </span>

            {% if page_obj.has_next %}
                <a class="btn btn-outline-success" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endif %}
<!-- Pagination ends -->

{% endblock %}

store/templates/store/login.html
{% extends 'store/base.html' %}
{% load static %}


{% block content %}


<style type="text/css">
    @media screen and (max-width: 480px){
    .img-container{
        width: 340px;
        padding: 5px;
    }
}

.login-form{
    border-radius: 0px !important;
    border: none;
}

img-container{
    object-fit: content;
}


</style>

    <div class="container mt-5 bg-white">
        <div class="row g-0">
            <div class="col">
                <img src="{% static 'background_images/signup.jpg' %}" alt="" height=464px width=700pxclass="img-container">
            </div>
            <div class="col">
                <div class="container">
                    <form class="form-control p-5 login-form" action="" method="POST">
                        <h4 class="mt-3 p-2" style="text-align: center;">Login Now</h4>
                        <label>Username</label></br>
                        <input type="text" class="form-control" name="username" placeholder="Enter Username"></br>
                        <label class="m-1">Password</label></br>
                        <input type="password" class="form-control" name="password" placeholder="Enter Password">
                        </br>
                        <button type="submit" class="btn btn-success col-lg-12 mt-4">Login</button>
                        </br>
                        <p class="mt-3">Don't have an account?<a href="{% url 'store:user_registration' %}" style="color:red;">sign up now</a></p>
                    </form>
                </div>
            </div>
        </div>
    </div>




{% endblock %}

store/templates/store/user_dashboard.html
{% extends "store/base.html" %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/user_dashboard.css' %}">

<div class="container my-5">
    <div class="dashboard__content">
        <!-- Dashboard sidebar starts -->
        <div class="dashboard__sidebar">
            <div class="card dashboard__card py-3">
                <div class="dashboard__topContent">
                    <span class="iconify dashboardUser__icon" data-icon="gridicons:user-circle" data-inline="false"></span>
                    <h5 class="fw-bold">{{ user.username }}</h5>
                </div>
                <div class="sidebar-widget-title py-0">
                    <span>Menu</span>
                </div>

                <!-- Dashboard sidebar link starts -->
                <div class="dashboard__links">
                    <ul>
                        <a class="text-muted" href="{% url 'store:dashboard' %}">
                            <li class="activeDash">
                                <span class="iconify icon" data-icon="clarity:dashboard-line" data-inline="false"></span> Dashboard
                            </li>
                        </a>
                        <a class="text-muted" href="{% url 'store:wishlist' %}">
                            <li>
                                <span class="iconify" data-icon="ant-design:heart-outlined" data-inline="false"></span> Wishlist
                            </li>
                        </a>
                        <a class="text-muted" href="{% url 'store:profile' %}">
                            <li>
                                <span class="iconify" data-icon="carbon:user" data-inline="false"></span> Manage Profile
                            </li>
                        </a>
                    </ul>
                </div>
                <!-- Dashboard sidebar link starts -->
            </div>
            <!-- Dashboard logout button starts -->
            <a class="w-100 btn btn-block btn-danger logout__btn" href="{% url 'store:logout' %}">Logout</a>
            <!-- dashboard logout button ends -->
        </div>
        <!-- Dashboard sidebar ends -->

        <!-- Dashboard right side content starts -->
        <div class="dashboard__dashboardContent">
            <div class="dashboard__header mb-2">
                <h5>Dashboard</h5>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a class="text-dark" href="{% url 'store:home' %}"><small>Home</small></a></li>
                        <li class="breadcrumb-item active" aria-current="page"><small>Dashboard</small></li>
                    </ol>
                </nav>
            </div>

            <div class="dashboard__table table-responsive">
                {% for order in request.user.orders.all %}
                <table class="table">
                    <thead class="table-dark">
                      <tr>
                        <th scope="col" style="text-align: center;">Order ID</th>
                        <th scope="col" style="text-align: center;">Product</th>
                        <th scope="col" style="text-align: center;">Quantity</th>
                        <th scope="col" style="text-align: center;">Price</th>
                        <th scope="col" style="text-align: center;">Payment</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for item in order.items.all %}
                        <tr>
                        <th scope="row" style="text-align: center;">{{item.id}}</th>
                        <td style="text-align: center;">{{item.product.title}}</td>
                        <td style="text-align: center">{{item.quantity}}</td>
                        {% if item.product.sale_price %}
                        <td style="text-align: center;">{{item.product.sale_price}}</td>
                        {% else %}
                        <td style="text-align: center;">{{item.product.market_price}}</td>
                        {% endif %}
                        <td style="text-align: center;">
                            <button class="btn btn-success">Make Payment</button>
                        </td>
                        </tr>
                        {% endfor %}
                    </tr>
                    </tbody>
                  </table>
                {% endfor %}
            </div>
        </div>
        <!-- Dashboard right side content ends -->
    </div>
</div>

{% endblock %}

store/templates/store/wishlist.html
{% extends "store/base.html" %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/wishlist.css' %}">

<div class="container my-5">
    <div class="dashboard__content">
        <!-- Dashboard sidebar starts -->
        <div class="dashboard__sidebar">
            <div class="card dashboard__card py-3">
                <div class="dashboard__topContent">
                    <span class="iconify dashboardUser__icon" data-icon="gridicons:user-circle" data-inline="false"></span>
                    <h5 class="fw-bold">Wasek Samin</h5>
                </div>
                <div class="sidebar-widget-title py-0">
                    <span>Menu</span>
                </div>

                <!-- Dashboard sidebar link starts -->
                <div class="dashboard__links">
                    <ul>
                        <a class="text-muted" href="{% url 'store:dashboard' %}">
                            <li>
                                <span class="iconify icon" data-icon="clarity:dashboard-line" data-inline="false"></span> Dashboard
                            </li>
                        </a>
                        <a class="text-muted" href="{% url 'store:wishlist' %}">
                            <li class="activeDash">
                                <span class="iconify" data-icon="ant-design:heart-outlined" data-inline="false"></span> Wishlist
                            </li>
                        </a>
                        <a class="text-muted" href="{% url 'store:profile' %}">
                            <li>
                                <span class="iconify" data-icon="carbon:user" data-inline="false"></span> Manage Profile
                            </li>
                        </a>
                    </ul>
                </div>
                <!-- Dashboard sidebar link ends -->
            </div>
            <!-- Dashboard sidebar ends -->

            <!-- Dashboard logout button starts -->
            <button class="w-100 btn btn-block btn-danger logout__btn">Logout</button>
            <!-- Dashboard logout button ends -->
        </div>
        <!-- Dashboard sidebar ends -->

        <!-- Dashboard right side content starts -->
        <div class="dashboard__Productcontainer">
            <div class="wishlist__header mb-2">
                <h5>Wishlist</h5>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                      <li class="breadcrumb-item"><a class="text-dark" href="{% url 'store:home' %}"><small>Home</small></a></li>
                      <li class="breadcrumb-item"><a class="text-dark" href="{% url 'store:dashboard' %}"><small>Dashboard</small></a></li>
                      <li class="breadcrumb-item active" aria-current="page"><small>Wishlist</small></li>
                    </ol>
                </nav>
            </div>
            {% if all_products %}
            <div class="product__category">
                {% for item in all_products %}
                <div class="card product__card {{ product.category.id }}">
                    <div class="product__info card-body mb-2">
                        <a class="text-dark" href="{% url 'store:product-detail' item.product.slug %}">
                            <h5 class="product__title">{{ item.product.title }}</h5>
                        </a>
                        {% if item.product.sale_price %}
                            <p><span class="text-muted cross__price">{{ item.product.market_price }}৳</span> <span>{{ item.product.sale_price }}৳</span></p>
                            {% else %}
                            <p>{{ item.product.market_price }}৳</p>
                        {% endif %}
                    </div>
                    <div class="product__bottom card-footer">
                        <button class="btn btn-danger">
                            <span class="iconify remove__icon" data-icon="codicon:trash" data-inline="false"></span>
                        </button>
                        <a href="{% url 'store:product-detail' item.product.slug %}">
                            <button class="btn__styled">View Details</button>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="card p-3 text-center">
                <h5 class="text-muted">No product to show!</h5>
            </div>
            {% endif %}
        </div>
        <!-- Dashboard right side content ends -->
    </div>
</div>

{% endblock %}